name: WallMagic
version: 1.0.0-RELEASE
main: com.juubes.wallmagic.WallMagic
authors: [Juubes]
description: A GenBucket plugin for Victorum.
website: https://parinacraft.net
depend: [Victorum]
commands:
  wallmagic:
  